sylius_grid:
    templates:
        action:
            view_conversions: "@SetonoSyliusGoogleAdsPlugin/grid/action/view_conversions.html.twig"
    grids:
        setono_sylius_google_ads_admin_connection:
            driver:
                name: doctrine/orm
                options:
                    class: "%setono_sylius_google_ads.model.connection.class%"
            fields:
                name:
                    type: string
                    label: sylius.ui.name
                enabled:
                    type: twig
                    label: sylius.ui.enabled
                    options:
                        template: "@SyliusUi/Grid/Field/enabled.html.twig"
            actions:
                main:
                    create:
                        type: create
                    view_conversions:
                        type: view_conversions
                        label: setono_sylius_google_ads.ui.view_conversions
                item:
                    update:
                        type: update
                    delete:
                        type: delete
