# Route responsible for redirecting the user to the 'correct' Google Ads page depending on the state of his/her setup
setono_sylius_google_ads_admin_redirect_main_menu:
    path: /
    methods: [GET]
    defaults:
        _controller: setono_sylius_google_ads.controller.action.redirect_main_menu
        
# Action that will retry a conversion
setono_sylius_google_ads_admin_retry_conversion:
    path: /conversions/{id}/retry
    methods: [GET]
    defaults:
        _controller: setono_sylius_google_ads.controller.action.retry_conversion

# Setup related routes
setono_sylius_google_ads_admin_setup_authorize:
    path: /connections/{connectionId}/setup/authorize
    methods: [GET]
    requirements:
        connectionId: '\d+'
    defaults:
        _controller: setono_sylius_google_ads.controller.action.setup_authorize
        
setono_sylius_google_ads_admin_setup_map_customer_id:
    path: /connections/{connectionId}/setup/map-customer-id
    methods: [GET,POST]
    requirements:
        connectionId: '\d+'
    defaults:
        _controller: setono_sylius_google_ads.controller.action.setup_map_customer_id
        
# OAuth related routes
setono_sylius_google_ads_admin_oauth_request:
    path: /oauth/request/{connectionId}
    methods: [GET]
    requirements:
        connectionId: '\d+'
    defaults:
        _controller: setono_sylius_google_ads.controller.action.oauth_request
        
setono_sylius_google_ads_admin_oauth_response:
    path: /oauth/response
    methods: [GET]
    defaults:
        _controller: setono_sylius_google_ads.controller.action.oauth_response

# Connection resource routes
setono_sylius_google_ads_admin_connection:
    resource: |
        section: admin
        alias: setono_sylius_google_ads.connection
        permission: true
        templates: '@SyliusAdmin\\Crud'
        redirect: update
        grid: setono_sylius_google_ads_admin_connection
        vars:
            all:
                subheader: setono_sylius_google_ads.ui.manage_connections
                templates:
                    form: "@SetonoSyliusGoogleAdsPlugin/connection/_form.html.twig"
            index:
                icon: 'linkify'
    type: sylius.resource
    
# Conversion resource routes
setono_sylius_google_ads_admin_conversion:
    resource: |
        section: admin
        alias: setono_sylius_google_ads.conversion
        permission: true
        templates: '@SyliusAdmin\\Crud'
        redirect: update
        grid: setono_sylius_google_ads_admin_conversion
        vars:
            all:
                subheader: setono_sylius_google_ads.ui.manage_conversions
                templates:
                    form: "@SetonoSyliusGoogleAdsPlugin/conversion/_form.html.twig"
            index:
                icon: 'money bill alternate outline'
    type: sylius.resource
