# todo remove
setono_sylius_google_ads_admin_oauth:
    path: /oauth/{connectionId}
    methods: [GET]
    requirements:
        connectionId: '\d+'
    defaults:
        _controller: setono_sylius_google_ads.controller.action.oauth
        connectionId: null

setono_sylius_google_ads_admin_connection:
    resource: |
        section: admin
        alias: setono_sylius_google_ads.connection
        permission: true
        templates: '@SyliusAdmin\\Crud'
        redirect: update
        grid: setono_sylius_google_ads_admin_connection
        vars:
            all:
                subheader: setono_sylius_google_ads.ui.manage_connections
                templates:
                    form: "@SetonoSyliusGoogleAdsPlugin/connection/_form.html.twig"
            index:
                icon: 'money bill alternate outline'
    type: sylius.resource
