imports:
    - "@SetonoSyliusGoogleAdsPlugin/Resources/config/grids/setono_sylius_google_ads_admin_conversion_action.yaml"

sylius_ui:
    events:
        sylius.admin.index:
            blocks:
                urls:
                    template: "@SetonoSyliusGoogleAdsPlugin/admin/block/help.html.twig"
                    priority: 15
